name: Build and Publish nginx Container Image

on:
  push:
    branches: [main]
  workflow_run:
    # Triggered by subsystem worflows
    workflows: ["Build Frontend"]
    types:
    - completed
    branches: [main]

jobs:
  check-status:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run'
    steps:
      - name: Check triggering workflow status
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Previous workflow failed. Exiting..."
            exit 1
          fi

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-status
    if: always() && (github.event_name == 'push' || (github.event_name == 'workflow_run' && needs.check-status.result == 'success'))
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/openparkproject/opp-nginx:latest