name: Build and Publish nginx Container Image

on:
  push:
    branches: [main]
  # Triggered by subsystems worflows
  repository_dispatch:
    types: [trigger-iac]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/openparkproject/opp-nginx:latest